### ISSUE TITLE
Possible to stop appending the ?hash to .vue files

### ISSUE THREAD

**Issue by wprater** [vuejs-templates/webpack-simple-2.0#13]
I like to add breakpoints in my Chrome Dev Tools, but since the HMR will add a hash `Component.vue?hash` when it reloads, I will lose context of my breakpoints making debugging a chore.  

I've spent some time trying to debug this and Im not certain if this is coming from vue-loader or within Webpack?  

I don't use a cache in devtools, so perhaps there can be a config option to stop the cache buster?

**Comment by yyx990803** [comment]
Unfortunately without the hash the source map will show stale source when modules are hot-reloaded. Also, in devtool break points won't work for `*.vue` files even if the hash is disabled, so it's likely caused by webpack itself rather than `vue-loader`.

`debugger` statements will work properly in the vue files though.
